#!/usr/bin/env ruby
# frozen_string_literal: true

# TODO: This should be improved. Maybe it's a good idea to start using a gemspec and bundle it as a gem rather than as
#       a ruby script.
$LOAD_PATH << '~/Desktop/Proyectos/todo/lib'
require 'todo'

options = ToDo::Parser.new(ARGV).parse
context = ToDo::Context.new(options)

if options.query
  ToDo::Finder.new(context: context, query: options.query).find
elsif options.visualize
  ToDo::Visualizer.new(context).view
else
  ToDo::Session.new(context).start
end
