#!/usr/bin/env ruby
# frozen_string_literal: true

require 'todo'

options = ToDo::Parser.new(ARGV).parse
context = ToDo::Context.new(options)

if options.query
  ToDo::Finder.new(context: context, query: options.query).find
elsif options.visualize
  ToDo::Visualizer.new(context).view
else
  ToDo::Session.new(context).start
end
